---
title: "CK010: Study Design"
summary: CK010
output:
  html_document:
    keep_md: true
    toc: true
    toc_float: true
    css: style.css

---



## Scientific errors and/or fraud

- [The staggering death toll of scientific lies](https://www.vox.com/future-perfect/368350/scientific-research-fraud-crime-jail-time)
- [The scandal of poor medical research (Altman 1994)](https://www.bmj.com/content/308/6924/283)
- [Methodology over metrics: current scientific standards are a disservice to patients and society (Van Calster et al 2021)](https://www.sciencedirect.com/science/article/pii/S0895435621001700)


## Questions before answers

- [A Second Chance to Get Causal Inference Right: A Classification of Data Science Tasks (Hernán, Hsu & Healy 2019](https://www.tandfonline.com/doi/full/10.1080/09332480.2019.1579578)
- [The C-Word: The More We Discuss It, the Less Dirty It Sounds (Hernan 2018)](https://ajph.aphapublications.org/doi/full/10.2105/AJPH.2018.304392)
- [Epidemiologic Methods Are Useless They Can Only Give You Answers (Kaufman and Hernan 2012)](https://journals.lww.com/epidem/Fulltext/2012/11000/Commentary___Epidemiologic_Methods_Are_UselessThey.3.aspx)
- [From ideas to studies: how to get ideas and sharpen them into research questions (Vandenbroucke & Pearce 2018)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5846748/) 
- [What is the question? (Yanai and Lercher 2019)](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1902-1)
- [Conceiving of Questions Before Delivering Analyses (Snowden, Reavis and Odden 2020)](https://pubmed.ncbi.nlm.nih.gov/32501813/)
- [Using Big Data to Emulate a Target Trial When a Randomized Trial Is Not Available (Hernan and Robins 2016)](https://pubmed.ncbi.nlm.nih.gov/26994063/)
- [Questions before answers (blog post)](https://www.jeremylabrecque.org/post/questions_before_answers)

## Causal inference

- [Causal Inference: What If? (Hernan and Robins 2020) ](https://www.hsph.harvard.edu/miguel-hernan/wp-content/uploads/sites/1268/2024/01/hernanrobins_WhatIf_2jan24.pdf)
- [Data, Design, and Bakground Knowledge in Etiologic Inference (Robins 2001)](https://pubmed.ncbi.nlm.nih.gov/11338312/)
- [Estimating Causal Effects (Maldonado and Greenland 2002)](https://academic.oup.com/ije/article/31/2/422/2951425)
- [Causation and Causal Inference in Epidemiology (Rothman and Greenland 2005)](https://ajph.aphapublications.org/doi/full/10.2105/AJPH.2004.059204)

## Causal assumptions


- [Understanding the Assumptions Underlying Instrumental Variable Analyses: a Brief Review of Falsification Strategies and Related Tools (Labrecque and Swanson 2018)](https://pubmed.ncbi.nlm.nih.gov/30148040/)
- [A Whirlwind Tour of Causal Assumptions (Labrecque 2024)](files/whirlwind.pdf)
- [Alternative causal inference methods in population health research: Evaluating tradeoffs and triangulating evidence (Matthay et al 2020)](https://pubmed.ncbi.nlm.nih.gov/31890846/)
- [History of the modern epidemiological concept of confounding (Morabia 2010)](https://jech.bmj.com/content/65/4/297)
- [Heuristic Thinking and Inference From Observational Epidemiology (Lash 2007)](https://journals.lww.com/epidem/fulltext/2007/01000/heuristic_thinking_and_inference_from.13.aspx)

## Causal diagrams

- [Causal Diagrams for Epidemiologic Research (Greenland, Pearl & Robins 1999)](https://journals.lww.com/epidem/Abstract/1999/01000/Causal_Diagrams_for_Epidemiologic_Research.8.aspx)
- [Reducing bias through directed acyclic graphs (Shrier & Platt 2008)](https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/1471-2288-8-70)

