---
title: "Essentials of Epidemiology (Causal Inference)"
author: "Jeremy Labrecque"
format:
  html:
    theme: none
    css: custom_5.css
    toc: true
    embed-resources: true
editor: visual
---

<br>

[You can find the slides here](https://kdrive.infomaniak.com/app/share/1502063/72356951-ab96-42e6-8214-887c4611e0f4).

Email me at j.labrecque@erasmusmc.nl

# 1. **Recognize** unclear research questions

-   [How and when to use causal and associational language](https://www.bmj.com/content/392/bmj-2025-085749.full) — Labrecque and Kezios 2026

    -   We felt that much of the writing criticizing the use of the word association didn't go far enough. Here we make the argument that it's not up to people advocating for causal language to convince people using associational language to change. The onus is on people using associational language to *explain what they mean* by the word association in their research question. We also provide guidelines for how to use causal and non-causal language.

-   [Descriptive estimands, causal estimands, and avoiding the jungle of adjusted associations 'in between'](https://jech.bmj.com/content/80/4/205) — Oberndorfer et al 2026

    -   The "jungle of adjusted associations" points out that when answering descriptive questions we sometimes choose to adjust for other variables. That means our question doesn't completely map onto a real-world description anymore.

-   [The distinction between causal, predictive, and descriptive research—there is still room for improvement](https://www.jclinepi.com/article/S0895-4356(25)00293-8/fulltext) — Dyer 2026

-   [Distinguishing Description, Prediction, and Causal Inference](https://www.neurology.org/doi/10.1212/WNL.0000000000210171) — Ito et al 2025

-   [Guidelines for reporting observational research in urology: the importance of clear reference to causality](https://bjui-journals.onlinelibrary.wiley.com/doi/full/10.1111/bju.16028) — Vickers et al 2023

-   [Is the Way Forward to Step Back? Documenting the Frequency With Which Study Goals Are Misaligned With Study Methods and Interpretations in the Epidemiologic Literature](https://academic.oup.com/epirev/article/43/1/4/6372079) — Kezios et al 2021

    -   This paper had a huge impact on me. The idea that over 2/3 of epidemiology articles in the top general epidemiology journals fell into a category called "seemingly causal" was a huge wake-up call. We are scientists — if there is one thing there is no excuse to be unclear about, it's our research questions. We need to do better.

-   [A Second Chance to Get Causal Inference Right: A Classification of Data Science Tasks](https://www.tandfonline.com/doi/full/10.1080/09332480.2019.1579578) — Hernán, Hsu & Healy 2019

    -   **Important paper:** This paper had a HUGE impact on many different fields. It made clear that all research tasks fall into the descriptive, predictive, and causal categories. If you can't figure out which category your paper falls into, then, I would argue, you don't understand your question well enough yet. I have been teaching this 3-task framework since this paper came out and have yet to encounter a question that doesn't fit.

-   [The C-Word: Scientific Euphemisms Do Not Improve Causal Inference From Observational Data](https://pubmed.ncbi.nlm.nih.gov/29565659/) — Hernán 2018

    -   This paper really got people thinking when it came out. It's the inspiration for the BMJ paper I wrote with Katrina Kezios at the top of this list, though we tried to make his arguments, along with a few others, in an even stronger way.

-   [Response to: "Associations Are Not Effects"](https://academic.oup.com/aje/article-abstract/134/4/442/121958?redirectedFrom=fulltext) — Savitz 1991

    -   The American Journal of Epidemiology used to cite a commentary written by [Petitti](https://pubmed.ncbi.nlm.nih.gov/1985440/) in 1991 to motivate their opposition to the use of causal language in their journal. But Savitz wrote a response to that article that makes many of the points people make today. If the AJE had used Savitz's paper as their reference instead of Petitti's, they would have been way ahead of their time!

# 2. **Construct** clear causal questions

-   [Using Big Data to Emulate a Target Trial When a Randomized Trial Is Not Available](https://pubmed.ncbi.nlm.nih.gov/26994063/) — Hernán & Robins 2016

-   [Observational studies analyzed like randomized experiments: an application to postmenopausal hormone therapy and coronary heart disease](https://pubmed.ncbi.nlm.nih.gov/18854702/) — Hernán et al 2008

- [Estimating causal effects](https://academic.oup.com/ije/article-abstract/31/2/422/2951425?redirectedFrom=fulltext) - Maldonado & Greenland 2002

    - This is the paper that inspired the fiction in my BMJ paper. It begins with a discussion with the "creator of the universe".

# 3. **Understand** the process of inferring causation from data

-   [Intuition for what causal assumptions do when adjusting for confounders (unpublished, do not distribute)](https://kdrive.infomaniak.com/app/share/1502063/1f0fa223-4ee1-41ae-a9c0-332213722422) - Labrecque

# 4. **Be aware of** popular tools for causal inference

### Directed acyclic graphs

-   [Reducing bias through directed acyclic graphs](https://pubmed.ncbi.nlm.nih.gov/18973665/) - Shrier and Platt 2008
-   [Chapter 6 in "What If?": Graphical representation of causal effects](https://miguelhernan.org/whatifbook) - Hernán & Robins 2025

### Instrumental variable analysis:

-   [An introduction to instrumental variables for epidemiologists](https://academic.oup.com/ije/article-abstract/29/4/722/765560?redirectedFrom=fulltext) - Greenland 2000
-   [Chapter 16 in "What If?": Instrumental variable estimation](https://miguelhernan.org/whatifbook) - Hernán & Robins 2025
- [A Gentle Introduction to Instrumental Variables](https://www.sciencedirect.com/science/article/pii/S0895435622001731) - Widding-Havneraas & Zachrisson 2022

### Regression discontinuity

- [Regression Discontinuity Designs in Epidemiology: A Practical Guide](https://pmc.ncbi.nlm.nih.gov/articles/PMC12581866/) - O'Keeffe & Petersen 2025   
- [Regression Discontinuity Designs in Epidemiology](https://pmc.ncbi.nlm.nih.gov/articles/PMC4162343/) - Bor et al 2014
- [An Introduction to Regression Discontinuity Design and Potential for Application in Neurology](https://www.neurology.org/doi/10.1212/WNL.0000000000214503) - Ahmed et al 2026
- [Regression Discontinuity for Causal Effect Estimation in Epidemiology](https://link.springer.com/article/10.1007/s40471-016-0080-x) - Oldenburg, Moscoe & Bärnighausen 2016

### Negative controls

-   [A Selective Review of Negative Control Methods in Epidemiology](https://pubmed.ncbi.nlm.nih.gov/33996381/) - Shi, Miao & Tchetgen Tchetgen 2020
- [Using Negative Control Populations to Assess Unmeasured Confounding and Direct Effects](https://journals.lww.com/epidem/abstract/2024/05000/using_negative_control_populations_to_assess.6.aspx) - Piccinini & Stensrud 2024
- [Negative Controls: A Tool for Detecting Confounding and Bias in Observational Studies](https://pmc.ncbi.nlm.nih.gov/articles/PMC3053408/) - Lipsitch, Tchetgen Tchetgen & Cohen 2011
