# Notation

If I could, I'd try to teach this course without notation because I know some people are intimidated by it. But I don't think it's to your advantage to learn the material without notation. There is math behind every aspect of epidemiology and public health just as much as there's biology and human behaviour present in our research fields. I also think that some notation will help you understand causal inference both on a practical and conceptual level.

If you're getting confused while reading this chapter, DON'T WORRY. You'll be fine. This will all make more sense when we're using these concepts. So I advise you to read this chapter and then refer to back to it when you encounter these concepts. 

## Variables

We use letters to represent variables. For example, in causal inference, we often use an $A$ to indicate the exposure[^1] and a $Y$ for the outcome. But these are just conventions. You are free to use whichever letter you'd like. You can use $Y$ for exposure and $A$ for the outcome if you want. There are no rules. Well, maybe one rule that you should always be clear about what a variable means. 

[^1]: The reason why $A$ is commonly used is because a lot of James Robins' work on causal inference in the 1980's focused on antiretroviral therapy as the treatment.

Uppercase letters used to indicate a random variable.[^2] A random variable can be thought of as the product of a stochastic process. In contrast,lowercase letters indicate a specific value of that variable. So $A$ might represent a binary variable with $0$'s representing untreated participants and $1$'s representing treated participants. Lowercase $a$ can then take the value $0$ or $1$. For example, if I write $a=1$ I'm referring to treatment and if I write $a=0$ I'm referring to the untreated condition. Sometimes we'll use $A=a=1$ (or $A=1$ for short) to refer to treated people. Or sometimes we'll use $a=1$ to indicate that we want to set a person's or a group of people's treatment to $1$. If this is feeling quite abstract at this point, it'll become clearer as you get through this chapter and, hopefully, even clearer when you start seeing how they're applied. 

[^2]: See this [Khan Academy video](https://www.khanacademy.org/math/statistics-probability/random-variables-stats-library/random-variables-discrete/v/random-variables) for a more in depth explanation of random variables.

## Expected value

You're going to see this letter $\textrm{E}$. It means the expected value of a series of numbers. For example, if I have measured the height of 10 people, the expected value of the height of those ten people is the average of their ten heights. We would write this like this $\textrm{E}[H]$ where $H$ is a vector of the people's heights. If the average height was 1.8m we could write $\textrm{E}[H]=1.8m$. When we talk about continuous variables we'll be using $\textrm{E}$ to talk about the average.

## Probability

When we talk about categorical or binary variable we're going to be talking about probabilities. Let's start with a binary variable. Say we have ten people, two of them are fans of the Montreal Canadiens[^3] and I don't know what's wrong with the rest of them. Let's say we have variable $C$ which is 1 for Canadiens fans and 0 for the others. The probability someone is a Canadiens is $\Pr[C=1]=0.2$.

[^3]: The [best](https://www.youtube.com/watch?v=ysDphYqMG6M) ice hockey team. 

## Conditioning


of a    I remember once I was attending a talk by someone who was presenting research done with a cohort of children. Many thousands of children. The presenter showed a result that had a very wide confidence interval, something like $\textrm{RR}=1.5 (95\% \textrm{ CI:} 0.8-2.7)$. So just a very noisy, inconclusive result. The best you can say with this result (assuming there's no bias and there always is) is that the exposure doesn't look to be either very protective or very harmful. But the presenter said that they had found that the exposure had no effect on the outcome. Again, I'm not trying to be too hard on this presenter because, as I said, this is a very very common error.

But then I think about it this way. They were using data on thousands of children which required those children and their thousands of parents to take time to go to the recruitment center and do the many things that are asked of participants when they're joining a cohort. This can involve measuring or asking very sensitive questions. All this very sensitive data is stored in a place that could leak (though this is rare). These thousands of parents and children give so much of themselves and this researcher could not even be bothered to learn how to properly interpret a significance test. I think it shows a total lack or respect for everything these people are giving to the cohort.

And my point extends to every other aspect of a study.

Now, you will make mistakes in your career. I have. Everyone does. Even when you're doing your aboslute best.
