# Confounding and confounders (Exchangeability part 1)

[Merriam-Webster defines](https://www.merriam-webster.com/dictionary/confounding) confounding as "to fail to discern differences between: mix up."[^1] When confounding is present, your analysis becomes confused because whatever estimate you find is a confusing mix between the causal effect and the confounding (and any other bias you might have).

[^1]: -1 point for starting a chapter with a dictionary definition.

Confounding is a critical topic in health sciences. If you don't understand confounding, you can't do causal inference. The better you understand confounding, the better you will be at your research. 

## Confound-ING

We'll begin by defining the phenomenon of confounding and in the next section define confounders. Confounding is present when you have a common cause of an exposure and an outcome and you haven't adjusted for any variables that could adjust for that confounding (more on this in the directed acyclic graph chapter).

```{r, engine = 'tikz', echo=FALSE}
\begin{tikzpicture}
\node[text centered] at (0,0) (a) {$A$};
\node[text centered] at (3,0) (y) {$Y$};
\node[text centered] at (0,2) (c1) {$C_1$};
\node[text centered] at (1.5,1) (c2) {$C_2$};
\draw[->, line width= 1] (a) -- (y);
\draw[->, line width= 1] (c1) -- (a);
\draw[->, line width= 1] (c1) -- (c2);
\draw[->, line width= 1] (c2) -- (y);
\end{tikzpicture}
```



## Confound-ER

If you've heard of a confounder before, you were likely taught that a confounder is a common cause of the exposure and the outcome.[^2] But it's easy to show that that

[^2]: I often like to think about words literally mean. A confounder, if you were very literal, should be the variable that is doing the confounding. In other words, a confounder should be a common cause. But if we decided to use this language we'd be stuck in a place where we'd have to admit that you could control for confounder by adjusting for a non-confounder. So really, there's no really satisfying way to use the language here.

## Other things

It's very common for people to talk about unmeasured confounding in their discussion section, often to remind you of its possible existence. As if we didn't know that. Anyway, unmeasured confounding is really the wrong way to say it. Sure an unmeasured confounder will bias your result. But so will a confounder that is poorly measured (e.g., controlling for obesity when the confounder is really BMI) or poorly modeled (e.g., failing to include age-squared when it was necessary). What we're really worried about is uncontrolled confounding.

## Resources
