# A whirlwind tour of causal assumptions

Confounding is just an old English word that is a synonym for confusing. Confounding is something that will confuse the answer you get to a causal question. For example, if the true RR is 1.4, if there is confounding present, the estimate you get will be something else than 1.4.

## Confound-ING

Confounding is present when you have a common cause of an exposure and an outcome and you haven't adjusted for any variables.

## Confound-ER

If you've heard of a confounder before, you were likely taught that a confounder is a common cause of the exposure and the outcome. But it's easy to show that that

\*Note (this is not essential to your knowledge): I often like to think about words literally mean. A confounder, if you were very literal, should be the variable that is doing the confounding. In other words, a confounder should be a common cause. But if we decided to use this language we'd be stuck in a place where we'd have to admit that you could control for confounder by adjusting for a non-confounder. So really, there's no really satisfying way to use the language here.

## Other things

It's very common for people to talk about unmeasured confounding in their discussion section, often to remind you of its possible existence. As if we didn't know that. Anyway, unmeasured confounding is really the wrong way to say it. Sure an unmeasured confounder will bias your result. But so will a confounder that is poorly measured (e.g., controlling for obesity when the confounder is really BMI) or poorly modeled (e.g., failing to include age-squared when it was necessary). What we're really worried about is uncontrolled confounding.

## Resources
