---
title: "Potential projects for NIHES Masters students"
summary: NIHES
output:
  html_document:
    keep_md: true
    css: style.css

---

Below you will find a short description of project ideas I've had in the back of my mind that would make nice Masters theses. All of these papers should easily result in a publication. Email me if you are interested in any of these projects: j [dot] labrecque [at] erasmusmc [dot] nl.

- **Review on the misuse of hypothesis testing in top clinical epidemiology journals:** This project would involve organizing and managing a systematic review of how p-values and hypothesis testing are abused in the top clinical epidemiology journals. As part of this project we will also recruit other students to do some of the full-text review of papers. [Sign-up to be a reviewer by clicking here.](https://docs.google.com/forms/d/e/1FAIpQLSdXQ19BkGLToTKlo2tRcRfDEuAT9YL2wO5Tg1X9qPwQsohKdA/viewform?usp=sf_link)

- **Estimating how intervening on lifestyle factors would change genetically determined risk of breast cancer using the UKBiobank:** This type of effect has not been estimated before. Some previous have attempted to but used the wrong answer. The results of this study would be of strong interest to women who know their genetics put them at higher risk of breast cancer. This project will involve using UKBiobank data.

- **PREPARE project:** This project would be with me and Dr. Jasper Been. Previous findings have found that the lockdown reduced pre-term birth by quite a large amount. Since then, many people have tried to find what it was about the lockdown that had this effect. A student in this project would study one of the potential hypotheses for the decrease in pre-term birth. 

- **Estimate how health inequalities change when we intervene in other places:** There are two goals to this project and the student would only have to do one. The first is to find an important applied example of a way to reduce health inequalities and estimate the effect of such an intervention. I already have code that is quite flexible to do this. The second goal is to take the code I've already developed and turn it into an R function that anyone can use. 

- **Is the risk ratio, odds ratios or risk difference more generalizable?**: A bit more of a mathy project but in some sense a straightforward project. People have long argued over whether risk differences, risk ratios or odds ratios are more generalizable. This project will involve simulating data to see which effect measure is most generalizable under which conditions. If there's time, the ideas in this project would ideally also be applied to applied data.

- **How should children from families with one Dutch parent and one parent from abroad be classified? As "Dutch" or "from abroad"?** The idea for this project started from another project looking at health inequalities. We were surprised to see more people are classifying these children as "from abroad" but there are good reasons to classify them as Dutch. This project will look at a number of important health inequalities and see the degree to which this matters or whether these children should be kept in their own category of "one Dutch parent".


