---
title: Keeper lists
summary: Here we describe how to add a page to your site.
date: ""

output:
  html_document:
    keep_md: true
    toc: true
    toc_float: true
    css: style.css
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(readr)
ds <- suppressMessages(read_csv("~/Google Drive/Personal/rhl/keeper_2324.csv"))

```



## Connor Dioxide Emissions

```{r}
library(knitr)
ds_ <- ds[,1:2]
ds_ <- ds_[!is.na(ds_[,1]),]
label <- ifelse(ds_[,2]>0,"Main","Farm")
kable(cbind(label,ds_), col.names = c("Main/farm","Player","Keeper cost"),row.names = F )
```


## Deluge of Gardseur

```{r}
library(knitr)
ds_ <- ds[,3:4]
ds_ <- ds_[!is.na(ds_[,1]),]
label <- ifelse(ds_[,2]>0,"Main","Farm")
kable(cbind(label,ds_), col.names = c("Main/farm","Player","Keeper cost"),row.names = F )
```


## Honey Badger DntCare

```{r}
library(knitr)
ds_ <- ds[,5:6]
ds_ <- ds_[!is.na(ds_[,1]),]
label <- ifelse(ds_[,2]>0,"Main","Farm")
kable(cbind(label,ds_), col.names = c("Main/farm","Player","Keeper cost"),row.names = F )
```

## Little Jarry

```{r}
library(knitr)
ds_ <- ds[,7:8]
ds_ <- ds_[!is.na(ds_[,1]),]
label <- ifelse(ds_[,2]>0,"Main","Farm")
kable(cbind(label,ds_), col.names = c("Main/farm","Player","Keeper cost"),row.names = F )
```


## Necas Fracas

```{r}
library(knitr)
ds_ <- ds[,9:10]
ds_ <- ds_[!is.na(ds_[,1]),]
label <- ifelse(ds_[,2]>0,"Main","Farm")
kable(cbind(label,ds_), col.names = c("Main/farm","Player","Keeper cost"),row.names = F )
```


## Suzuki Jimney

```{r}
library(knitr)
ds_ <- ds[,11:12]
ds_ <- ds_[!is.na(ds_[,1]),]
label <- ifelse(ds_[,2]>0,"Main","Farm")
kable(cbind(label,ds_), col.names = c("Main/farm","Player","Keeper cost"),row.names = F )
```


## Mon Hockey

```{r}
library(knitr)
ds_ <- ds[,13:14]
ds_ <- ds_[!is.na(ds_[,1]),]
label <- ifelse(ds_[,2]>0,"Main","Farm")
kable(cbind(label,ds_), col.names = c("Main/farm","Player","Keeper cost"),row.names = F )
```


## Стивен Прекрасный

```{r}
library(knitr)
ds_ <- ds[,15:16]
ds_ <- ds_[!is.na(ds_[,1]),]
label <- ifelse(ds_[,2]>0,"Main","Farm")
kable(cbind(label,ds_), col.names = c("Main/farm","Player","Keeper cost"),row.names = F )
```