---
title: "Erasmus MC Causal Inference Group"
summary: Causal Inference Group
output:
  html_document:
    keep_md: true
    css: style.css

---



We meet every second Wednesday in NA2803 at ErasmusMC and through Teams if you're not in Rotterdam.

You can also email me if you are interested in causal inference and would like to join our meetings: j [dot] labrecque [at] erasmusmc [dot] nl.

## 2024 Schedule

Link to [Causal Inference: What if?](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/)


### Winter/spring 2025

|Date|Topic|
|:------ |:------ |
|January 8||


### Fall 2024

|Date|Topic|
|:------ |:------ |
|September 4|Chapter 23 from What if: Mediation|
|September 18|Chang presenting about the difference between Rubin and Pearl|
|October 2||
|October 16||
|October 30|Jeremy returns|
|November 13|[Without Commitment to an Ontology, There Could Be No Causal Inference](https://pubmed.ncbi.nlm.nih.gov/35383645/)|
|November 27|Keling's MSc thesis defense: Causal language use in clinical practice guidelines for diabetes mellitus: evaluation of causality and alignments|
|December 4| Maurice will talk about selection diagrams|


### Winter/Spring 2024

|Date|Topic|
|:------ |:------ |
|January 10| Chatper 12 from What if: IPTW and outcome regression|
|January 24|Sjoerd midterm presentation|
|February 7||
|Februrary 21||
|March 6|Nina: TMLE|
|March 20|Maurice: Estimands in decision models|
|April 3|Chapter 14 from What If: G-estimation of structural nested models|
|April 17|Chang presenting about consistency|
|May 1|Chapter 13 from What If: Standardization and the parametric g-formula|
|May 15||
|May 29||
|June 12||
|June 26||




