---
title: "Why the word 'association' should not be in your research question"
summary: Weon poster
output:
  html_document:
    keep_md: false
    toc: true
    toc_float: true
    css: style.css

---

</br>


JA Labrecque (j.labrecque@erasmusmc.nl), KL Kezios


</br>

### There are many associations you can estimate, which one is the association you are interested in?
Often people say they are interested in 'the' or 'an' association between an exposure and outcome. But which association is 'the' association? There are many, many different associations you can estimate between two variables: a crude association, an association adjusted for some variables, an association adjusted for other variables, a non-linear association. When people say things like they're interested in 'the' association, they are not telling you which of these they are interested in. 

You might say, "Well what we mean is the association adjusted for as many confounders as possible." If that's what is meant, why not just say one is interested in the causal effect? There's no other reason to try to eliminate all confounding unless you're targeting a causal effect. So just be honest about your question instead of using ambiguous language.

### You can't know which association you're interested in ahead of time
This is especially apparent when people do variable selection. For example you might use a causal graph to decide, of all the variables you measured, which ones you need to adjust for. If your methods section talks about how you're going to select adjustment variables, _then you cannot tell me ahead of time which association you're interested in because you only know that once you decide what you will adjust for_. You might say, "Ok. I see your point but what if we chose the adjustment variables first and then state the research question as the association adjusted for those variables?" First it is strange that you would apply variable selection, something which belongs in the methods section of a paper, to define the research question. Second, if I ask you why you chose the kind of variable selection you did, you cannot tell me because it answers your research question because it is defining your research question.

If you did define your adjustment variables beforehand, you run into another problem: how do you talk about bias? If you say I want to estimate the association between X and Y adjusted for A, B and C and you've measured A, B and C, is there then no uncontrolled confounding? You've adjusted for all the same variables that appear in your research question! So where would uncontrolled or unmeasured confounding come from?

### The way out

Let's just call things what they are. If you are interested in knowing the causal effect of X on Y, just say so. Just remember that the true causal effect is unknowable. The best we can do is try to estimate it with data and causal assumptions. For example, one valid research goal might be to estimate the causal effect of taking vitamin B supplements on 5-year dementia risk. The number I get from my analysis won't be the causal effect but it is nonetheless what my research aim is.

When you're talking about the numbers your analyses give you, those are associations. They are describing specific relationships between variables. For example, you could say that the association between taking vitamin B supplements and 5-year dementia risk after adjusting for ten variables you have measured is a risk ratio of 0.8. You are not making any claim beyond saying that this is the numerical relationship between these variables. 

If you want to interpret those associations while simultaneously making causal assumptions (e.g., exchangeability, positivity and consistency), now what you have are estimated causal effects. For example, assuming exchangeability, positivity and consistency, the estimated causal effect of taking vitamin B supplements on 5-year dementia risk is a risk ratio of 0.8. 

### A way ahead for journal editors

The answer is never to ban language. The word association has a role to play. The answer is something, I think, most journal editors will say they already do: ban unclear research questions. If journal editors, upon reading an article title or research question such as, "the association between X and Y," they can simply respond, "you must clarfiy which association is 'the' association for this question to be clear." The authors will quickly run into the problems described above and find that they cannot ask a clear question while using the word association. 


### Asking a causal question does not make your answer more causal

Asking a causal question makes your question clearer, it makes it clearer what you have to do to answer this question and makes it easier to think about potential biases. Asking a causal question does not give your answer a causal interpretation. The only thing that can guarantee your answer is causal is that the causal assumptions that underlie your analysis are satisfied. And that is something you cannot guarantee. So the extent to which we believe that an estimated causal effect is equal to the true causal effect is the extent to which your arguments for the causal assumptions are believable.   

### Descriptive questions

If the underlying question is truly descriptive, then using the word association in the research question may be possible. We prefer to reserve the word association for describing numerical relationships between variables, i.e. the means to end rather than an end in itself. We also think that any descriptive question phrased as an association can be more clearly posed without the word association. For example, someone might want to know the association between gender and the incidence of pancreatic cancer. Would the question not be clearer by asking about the difference in the incidence of pancreatic between different genders?