---
title: "Readings for topics in epidemiology"
summary: Here we describe how to add a page to your site.
output:
  html_document:
    keep_md: false
    toc: true
    toc_float: true
    css: style.css

---

</br>
</br>

## General causal inference

- Pearl J. [The Foundations of Causal Inference](https://ftp.cs.ucla.edu/pub/stat_ser/r355-reprint.pdf). 2010.

- Lundberg I, Johnson R, Stewart BM. [What Is Your Estimand? Defining the Target Quantity Connects Statistical Evidence to Theory.](https://journals.sagepub.com/doi/10.1177/00031224211004187) American Sociological Review. 2021;86(3):532-565.

  >"We make only one point in this article. Every quantitative study must be able to answer the question: what is your estimand?"

- Hernán, Miguel A. "[The C-word: scientific euphemisms do not improve causal inference from observational data.](https://ajph.aphapublications.org/doi/10.2105/AJPH.2018.304392)" American journal of public health 108.5 (2018): 616-619.

- T[witter thread by Paul Zivich on Robin's 1986 landmark paper](https://twitter.com/PausalZ/status/1328153586983981061)
  
## General epidemiology 

- Stang, A., Standl, F. & Poole, C. A twenty-first century perspective on concepts of modern epidemiology in Ignaz Philipp Semmelweis’ work on puerperal sepsis. Eur J Epidemiol (2022). https://doi.org/10.1007/s10654-022-00871-8

## Cross sectional studies

- David A Savitz, Gregory A Wellenius, [Can Cross-Sectional Studies Contribute to Causal Inference? It Depends](https://academic.oup.com/aje/advance-article-abstract/doi/10.1093/aje/kwac037/6539984), American Journal of Epidemiology, 2022.      

  **Summary:** Argues that cross-sectional studies are not necessarily all bad. Presents three important considerations when interpreting/conducting cross-sectional studies but doesn't really go into any detail about how to interpret numerical estimates of such studies. 
  
- Hudson JI, Pope HG Jr, Glynn RJ. [The cross-sectional cohort study: an underutilized design](https://pubmed.ncbi.nlm.nih.gov/15824552/), Epidemiology, 2005  


## G methods

Ashley I Naimi, PhD, Stephen R Cole, PhD, Edward H Kennedy, PhD, [An introduction to g methods](https://academic.oup.com/ije/article/46/2/756/2760169), International Journal of Epidemiology, 46(2), 2017, 756–762


## Causal graphs

Tennant et al. Use of directed acyclic graphs (DAGs) to identify confounders in applied health research: review and recommendations, International Journal of Epidemiology, Volume 50, Issue 2, April 2021, Pages 620–632, https://doi.org/10.1093/ije/dyaa213


## Bias analysis

- Greenland S. [Invited Commentary: Dealing With the Inevitable Deficiencies of Bias Analysis—and All Analyses](https://academic.oup.com/aje/article/190/8/1617/6189732), American Journal of Epidemiology, 2021

- MacLehose RF, Ahern TP, Lash TL, Poole C, Greenland S. [The Importance of Making Assumptions in Bias Analysis](https://journals.lww.com/epidem/Fulltext/2021/09000/The_Importance_of_Making_Assumptions_in_Bias.1.aspx), Epidemiology, 2021


## Video/audio

- [Judea Pearl on the Mindscape podcast](https://www.preposterousuniverse.com/podcast/2022/05/09/196-judea-pearl-on-cause-and-effect/)

- [Online Causal Inference Seminar](https://www.youtube.com/channel/UCiiOj5GSES6uw21kfXnxj3A/videos)

- [Jamie Robins: Causal Inference without randomized experiments: How do we know we are right?](https://www.youtube.com/watch?v=Joma9vbstsA) 

- [Charles Manski: Communicating Uncertainty in Policy Analysis](https://www.youtube.com/watch?v=VSxOsR9-qwQ)


## Books

- [_Causal Inference: What If_](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/) by Hernan and Robins.

- [_The Effect_](https://theeffectbook.net/) by Nick Huntington-Klein

- [_Epidemiology by Design_](https://global.oup.com/academic/product/epidemiology-by-design-9780190665760?cc=us&lang=en&) by Daniel Westreich 

## Hypothesis testing/p-values

- Berner, D., & Amrhein, V. (2022). [Why and how we should join the shift from significance testing to estimation.](https://doi.org/10.1111/jeb.14009) Journal of Evolutionary Biology, 00, 1– 11.